#!/usr/bin/env node
'use strict';

// TODO: use bundled output in official UI, switch Typescript version to generate modern JS

const Bundler = require('../bundler');
const bundler = new Bundler(__dirname);

// calc/data
let bundled = `(() => {
'use strict';
const exports = {};
`;
bundled += bundler.read('util.js', 3, 1);
const species = bundler.read('data/species.js').split('\n');
bundled += species.slice(1, 39).join('\n'); // generator + iterator polyfill
bundled += '\nvar e_1, _a, e_2, _b;\nvar util_1 = exports;\n';
bundled += species.slice(43, -2).join('\n');

const types = bundler.read('data/types.js').split('\n');
bundled += types.slice(1, 12).join('\n'); // __assign polyfill
bundled += types.slice(54, -2).join('\n')
const natures = bundler.read('data/natures.js').split('\n');
bundled += natures.slice(28, 44).join('\n'); // __read polyfill
bundled += natures.slice(47, -2).join('\n');
bundled += bundler.read('data/abilities.js', 43, 1);
bundled += bundler.read('data/moves.js', 43, 1);
const items = bundler.read('data/items.js').split('\n');
bundled += items.slice(44, 53).join('\n'); // spreadArray polyfill
bundled += items.slice(68, -2).join('\n');
bundled += `
var abilities_1 = exports;
var items_1 = exports;
var moves_1 = exports;
var species_1 = exports;
var types_1 = exports;
var natures_1 = exports;
`;
bundled += bundler.read('data/index.js', 9, 1);
bundled += `
// EXPORTS
window.calc = Object.assign(window.calc || {}, {
  Generations: exports.Generations,
  ABILITIES: exports.ABILITIES,
  ITEMS: exports.ITEMS,
  MEGA_STONES: exports.MEGA_STONES,
  MOVES: exports.MOVES,
  SPECIES: exports.SPECIES,
  NATURES: exports.NATURES,
  TYPE_CHART: exports.TYPE_CHART,
});
})();`
bundler.bundle(bundled, 'data/production.min.js');

// calc
bundled = `(() => {
  'use strict';
  const exports = {};
  `;
bundled += bundler.read('util.js', 3, 1);
bundled += '\nvar util_1 = exports;\n';
bundled += bundler.read('stats.js', 4, 1);
bundled += '\nvar stats_1 = exports;\n';
const pokemon = bundler.read('pokemon.js').split('\n');
bundled += pokemon.slice(1, 23).join('\n'); // __assign + iterator polyfill
bundled += pokemon.slice(27, -2).join('\n');
const field = bundler.read('field.js').split('\n');
bundled += field.slice(1, 17).join('\n'); // __read polyfill
bundled += field.slice(19, -2).join('\n');
bundled += bundler.read('move.js', 4, 1);
bundled += bundler.read('items.js', 4, 1);
const utils = bundler.read('mechanics/util.js').split('\n');
bundled += utils.slice(28, 37).join('\n'); // spreadArray polyfill
bundled += utils.slice(41, -2).join('\n');
bundled += bundler.read('result.js', 29, 1);
bundled += '\nvar result_1 = exports;\nvar util_2 = exports;\n';
bundled += bundler.read('desc.js', 22, 1);
bundled += '\nvar desc_1 = exports;\nvar items_1 = exports;\n';
bundled += bundler.read('mechanics/gen78.js', 7, 1);
bundled += bundler.read('mechanics/gen56.js', 7, 1);
bundled += bundler.read('mechanics/gen4.js', 31, 1);
// These don't require 'util', so 'mechanics/util' gets the util_1 name.
bundled += bundler.read('mechanics/gen3.js', 31, 1).replace(/util_1/g, 'util_2');
bundled += bundler.read('mechanics/gen12.js', 31, 1).replace(/util_1/g, 'util_2');
bundled += `
var field_1 = exports;
var gen12_1 = exports;
var gen3_1 = exports;
var gen4_1 = exports;
var gen56_1 = exports;
var gen78_1 = exports;
`;
bundled += bundler.read('calc.js', 9, 1);

bundled += `
// EXPORTS
window.calc = Object.assign(window.calc || {}, {
  Field: exports.Field,
  Side: exports.Side,
  Pokemon: exports.Pokemon,
  Move: exports.Move,
  calculate: exports.calculate,
  Result: exports.Result,
  toID: exports.toID,
  STATS: exports.STATS,
  Stats: exports.Stats,
});
})();`
bundler.bundle(bundled);