import * as I from './data/interface';
export declare class Move {
    gen: I.Generation;
    name: string;
    originalName: string;
    ability?: I.AbilityName;
    item?: I.ItemName;
    species?: I.SpeciesName;
    useZ?: boolean;
    useMax?: boolean;
    overrides?: Partial<I.Move>;
    hits: number;
    usedTimes?: number;
    metronomeCount?: number;
    bp: number;
    type: I.TypeName;
    category: I.MoveCategory;
    hasSecondaryEffect: boolean;
    isSpread: boolean | 'allAdjacent';
    makesContact: boolean;
    hasRecoil?: I.MoveRecoil;
    isCrit: boolean;
    givesHealth: boolean;
    percentHealed?: number;
    ignoresBurn: boolean;
    isPunch: boolean;
    isBite: boolean;
    isBullet: boolean;
    isSound: boolean;
    isPulse: boolean;
    hasPriority: boolean;
    dropsStats?: number;
    ignoresDefenseBoosts: boolean;
    dealsPhysicalDamage: boolean;
    bypassesProtect: boolean;
    isZ: boolean;
    isMax: boolean;
    usesHighestAttackStat: boolean;
    constructor(gen: I.Generation, name: string, options?: {
        ability?: I.AbilityName;
        item?: I.ItemName;
        species?: I.SpeciesName;
        useZ?: boolean;
        useMax?: boolean;
        isCrit?: boolean;
        hits?: number;
        usedTimes?: number;
        metronomeCount?: number;
        overrides?: Partial<I.Move>;
    });
    clone(): Move;
}
export declare function getZMoveName(moveName: string, moveType: I.TypeName, item?: string): string;
export declare function getMaxMoveName(moveType: I.TypeName, pokemonSpecies?: string, isStatus?: boolean): string;
