#!/bin/bash -ex

# Setup

TMP=$(mktemp -qdt "$(basename $0).XXXXXX" 2>/dev/null || mktemp -q -d)
trap "rm -rf $TMP" 0

rev=$(git rev-parse --short HEAD | tr -d "\n")

# Build

node build
cp -a dist/ $TMP

# Checkout: master -> gh-pages

git checkout gh-pages

# Publish

cp -a $TMP/* .

git add -A .
git commit -m "Publish: '${rev}'"
git push git@github.com:smogon/damage-calc.git --force gh-pages

# Checkout: gh-pages -> master

git checkout -
