#!/usr/bin/env node

require('source-map-support').install();
const path = require('path');
const importer = require('./dist/index');

const dir = path.resolve(__dirname, process.argv[2] || '../src/js/data');
(async () => { await importer.importSets(dir); })().catch(console.error);