#!/usr/bin/env node

const Dex = require('../../Pokemon-Showdown/.sim-dist/dex').Dex;

const TIERS = {};

for (let gen = 1; gen <= 8; gen++) {
	const dex = Dex.forFormat('gen' + gen + 'ou');
	for (const k in dex.data.Pokedex) {
		const val = dex.getTemplate(k);
		if (!val || (typeof val.exists === 'boolean' && !val.exists) || val.gen > gen) continue;
		if (val.tier === 'Unreleased') continue;
		if (val.tier === 'Illegal' && (gen < 8 || TIERS[7][Dex.getId(val)] !== 'Uber')) continue;
		if (val.tier.startsWith('CAP') && gen < 4) continue;
		TIERS[gen] = (TIERS[gen] || {});
		TIERS[gen][Dex.getId(val)] = val.tier;
	}
}

console.log(JSON.stringify(TIERS, null, 2));
