#!/usr/bin/env node

const calc = require('../calc/dist/index');
const Dex = require('../../Pokemon-Showdown/.sim-dist/dex').Dex;

const MISSING = {};

for (let gen = 1; gen <= 7; gen++) {
	const dex = Dex.forFormat('gen' + gen + 'ou');
	for (const k in dex.data.Items) {
		const val = dex.getItem(k);
		if (!val || (typeof val.exists === 'boolean' && !val.exists) || val.gen !== gen) continue;
		if (val.name.endsWith(' Ball') || val.name.endsWith(' Stone') || val.name.startsWith('Power ')) continue;
		if (val.name.endsWith(' Fossil')) continue;
		if (!calc.ITEMS[gen].includes(val.name)) MISSING[k] = val.name;
	}
	for (const k in dex.data.Abilities) {
		const val = dex.getAbility(k);
		if (!val || (typeof val.exists === 'boolean' && !val.exists) || val.gen !== gen) continue;
		if (!calc.ABILITIES[gen].includes(val.name)) MISSING[k] = val.name;
	}
	for (const k in dex.data.Movedex) {
		const val = dex.getMove(k);
		if (!val || (typeof val.exists === 'boolean' && !val.exists) || val.gen !== gen) continue;
		if (!calc.MOVES[gen][val.name]) MISSING[k] = val.name;
	}
}

console.log(JSON.stringify(MISSING, null, 2));
