import { Generation, TypeName, NatureName } from '../data/interface';
import { Field, Side, Weather } from '../field';
import { Move } from '../move';
import { Pokemon } from '../pokemon';
import { StatsTable } from '../stats';
export declare function isGrounded(pokemon: Pokemon, field: Field): boolean;
export declare function getModifiedStat(stat: number, mod: number, gen?: Generation): number;
export declare function getFinalSpeed(gen: Generation, pokemon: Pokemon, field: Field, side: Side): number;
export declare function pokeRound(num: number): number;
export declare function getMoveEffectiveness(gen: Generation, move: Move, type: TypeName, isGhostRevealed?: boolean, isGravity?: boolean): number;
export declare function checkAirLock(pokemon: Pokemon, field: Field): void;
export declare function checkForecast(pokemon: Pokemon, weather?: Weather): void;
export declare function checkKlutz(pokemon: Pokemon): void;
export declare function checkIntimidate(source: Pokemon, target: Pokemon): void;
export declare function checkDownload(source: Pokemon, target: Pokemon): void;
export declare function checkIntrepidSword(source: Pokemon): void;
export declare function checkInfiltrator(pokemon: Pokemon, affectedSide: Side): void;
export declare function checkSeedBoost(pokemon: Pokemon, field: Field): void;
export declare function chainMods(mods: number[]): number;
export declare function getBaseDamage(level: number, basePower: number, attack: number, defense: number): number;
export declare function getFinalDamage(baseAmount: number, i: number, effectiveness: number, isBurned: boolean, stabMod: number, finalMod: number, protect?: boolean): number;
export declare function getWeightFactor(pokemon: Pokemon): 1 | 2 | 0.5;
export declare function countBoosts(gen: Generation, boosts: StatsTable): number;
export declare function getEVDescriptionText(gen: Generation, pokemon: Pokemon, stat: 'atk' | 'def' | 'spd' | 'spa', natureName: NatureName): string;
